# Generated by Django 5.1.2 on 2024-11-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='horario',
            new_name='horario_desde',
        ),
        migrations.AddField(
            model_name='reservas',
            name='horario_hasta',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
