# Generated by Django 5.1.2 on 2024-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_horario_reservas_horario_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10),
        ),
    ]
