services:
  django:
    image: backend:0.2
    build:
      context: ./config/django-image
    volumes:
      - ./backend:/usr/src/app:delegated
    environment:
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
    ports:
      - 8000:8000
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
      - ./conf/postgres/:/docker-entrypoint-initdb.d/
  frontend:
      image: node:lts
      working_dir: /app
      ports:
          - "5173:5173"
      volumes:
      - ./frontend/:/app
      tty: true
      command: sh -c "npm install && npm run dev"
  redis:
    image: redis:alpine
    command: sh -c 'redis-server'
    ports:
      - 6379:6379
  celery:
    build:
      context: ./config/django-image
    command: celery -A app worker --loglevel=info 
    volumes:
      - ./backend:/usr/src/app:delegated
    environment:
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
      - django

  celery_beat:
    build:
      context: ./config/django-image
    command: celery -A app beat --loglevel=info
    volumes:
      - ./backend:/usr/src/app:delegated
    environment:
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
      - django
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_USERNAME=${DATABASE_USER}
      - ADMINER_DEFAULT_PASSWORD=${DATABASE_PASS}