# Generated by Django 5.1.2 on 2024-10-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canchas',
            name='descripcion',
            field=models.TextField(max_length=1086),
        ),
        migrations.AlterField(
            model_name='canchas',
            name='nombre',
            field=models.CharField(max_length=48),
        ),
    ]
