# Generated by Django 5.1.2 on 2024-11-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_canchas_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='canchas',
            name='tipo',
            field=models.CharField(default='5 vs 5', max_length=48),
            preserve_default=False,
        ),
    ]
