# Generated by Django 5.1.2 on 2024-11-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0003_canchas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='canchas',
            name='precio',
            field=models.IntegerField(default=10.0),
            preserve_default=False,
        ),
    ]
